services:
  db:
    image: postgres:16.6-alpine3.21
    restart: always
    shm_size: 128mb
    volumes:
      - postgresdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgresdb:
